global:
  scrape_interval: 5s  # Intervalo de coleta para todos os jobs

rule_files:
  - "alert.rules.yml"

scrape_configs:

  # ICMP com Blackbox Exporter
  - job_name: 'icmp_ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - google.com
          - youtube.com
          - facebook.com
          - instagram.com
          - whatsapp.com
          - globo.com
          - openai.com
          - cloudflare.com
          - rpnet.sgp.net.br
          - rpnet2.sz.chat
          - zabbix.com
          - 8.8.8.8
          - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # HTTP com Blackbox Exporter (2xx)
  - job_name: 'blackbox_http'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]

    static_configs:
      - targets:
          - https://www.netflix.com
          - https://www.samsung.com
          - https://www.apple.com
          - https://www.gov.br

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
      - target_label: __metrics_path__
        replacement: /probe
      - target_label: job
        replacement: blackbox_http
      - source_labels: [__param_target]
        regex: https://(?:www\.)?(.*)
        replacement: $1
        target_label: instance