{
 "title": "Monitoramento HTTP & ICMP",
 "refresh": "30s",
 "panels": [
  {
   "title": "Status Ping (Sucesso)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"icmp_ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taxa de Sucesso em 5m",
   "type": "stat",
   "description": "Taxa de sucesso do ICMP nos últimos 5 minutos",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"icmp_ping\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latência HTTP (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox_http\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}